name: cross_p2p_network
description: A cross-platform Flutter plugin for P2P attendance systems with Wi-Fi Aware and hotspot support
version: 1.0.1
homepage: https://github.com/KritishBokde91/cross_p2p_network

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  connectivity_plus: ^7.0.0
  convert: ^3.1.2
  crypto: ^3.0.6
  dev: ^1.0.0
  device_info_plus: ^12.1.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.1
  mqtt5_client: ^4.14.0
  mqtt_client: ^10.11.1
  network_info_plus: ^7.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  platform_device_id: ^1.0.1
  plugin_platform_interface: ^2.0.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  stream_transform: ^2.1.1
  uuid: ^4.5.1
  wifi_info_flutter: ^2.0.2
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  coverage: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: com.upasthiti.cross_p2p_network
        pluginClass: CrossP2pNetworkPlugin
      ios:
        pluginClass: CrossP2pNetworkPlugin

topics:
  - networking
  - p2p
  - wifi
  - offline
  - attendance